default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fluffy_scheduler

test:
  <<: *default
  database: fluffy_scheduler_test

staging:
  <<: *default
  database: fluffy_scheduler_staging

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>